plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
    id 'eclipse'
    id "org.springframework.boot" version "3.3.0"
    id 'io.spring.dependency-management' version '1.1.5'
    id 'org.jetbrains.kotlin.jvm' version '1.8.20'
    id "io.swagger.core.v3.swagger-gradle-plugin" version "2.2.22"
}


java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}


repositories {
    // Use maven central for resolving dependencies.
    mavenCentral()

    maven {
        url 'https://repo.maven.apache.org/maven2'
        metadataSources {
            mavenPom()
            artifact()
        }
    }

    maven {
        url 'https://jcenter.bintray.com'
        url 'https://jitpack.io'
        url "https://plugins.gradle.org/m2/"
    }

}

dependencies {

	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-tomcat'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-api:2.6.0'

    implementation 'org.glassfish.jersey.core:jersey-server:3.0.2' 
    implementation 'org.glassfish.jersey.containers:jersey-container-servlet:3.0.2' 
    implementation 'org.glassfish.jersey.media:jersey-media-multipart:3.0.2' 
    implementation 'org.glassfish.tyrus.bundles:tyrus-standalone-client:1.15'

    implementation 'commons-io:commons-io:2.11.0'
    implementation 'org.java-websocket:Java-WebSocket:1.5.2'

    implementation 'com.knuddels:jtokkit:0.6.1'
    implementation 'org.json:json:20171018'
    
    implementation 'com.nimbusds:oauth2-oidc-sdk:10.4'

    implementation 'org.web3j:core:5.0.0'

    implementation 'javax.ws.rs:javax.ws.rs-api:2.1.1'
	implementation 'javax.websocket:javax.websocket-api:1.1'

    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.8.20'

    implementation('org.apache.commons:commons-dbcp2:2.9.0'){
    exclude module: "asm"
    exclude module: "asm-commons"
        }

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

    // Use JUnit test framework.
    testImplementation "junit:junit:4.13.2"
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// testImplementation 'org.springframework.security:spring-security-test'
}


bootJar {
    mainClassName = "${project.property('service.name')}.${project.property('service.class')}"
}

application {
    // Define the main class for the application.
    mainClass = "${project.property('service.name')}.${project.property('service.class')}"

    group = "${project.property('service.name')}"
    archivesBaseName = group

    version = "${project.property('service.version')}"
    sourceCompatibility = "${project.property('java.version')}"
    targetCompatibility = "${project.property('java.version')}"
}

springBoot {
    mainClassName = "${project.property('service.name')}.${project.property('service.class')}"
}


tasks.named('test') {
  useJUnitPlatform()
}
