plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
    id 'eclipse'
    id "org.springframework.boot" version "3.3.0"
    id 'io.spring.dependency-management' version '1.1.5'
    id 'org.jetbrains.kotlin.jvm' version '1.8.20'
    id "io.swagger.core.v3.swagger-gradle-plugin" version "2.2.22"
}

repositories {
    // Use maven central for resolving dependencies.
    mavenCentral()

    maven {
        url 'https://repo.maven.apache.org/maven2'
        metadataSources {
            mavenPom()
            artifact()
        }
    }

    maven {
        url 'https://jcenter.bintray.com'
        url 'https://jitpack.io'
        url "https://plugins.gradle.org/m2/"
    }

}


dependencies {

	implementation 'org.springframework.boot:spring-boot-starter-web'

	runtimeOnly 'org.postgresql:postgresql'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'org.springdoc:springdoc-openapi-ui:1.6.14'
    implementation 'org.springdoc:springdoc-openapi-data-rest:1.6.14'
    implementation 'org.springdoc:springdoc-openapi-javadoc:1.6.14'
    // implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'

    implementation 'org.glassfish.jersey.core:jersey-server:3.0.2' 
    implementation 'org.glassfish.jersey.containers:jersey-container-servlet:3.0.2' 
    implementation 'org.glassfish.jersey.media:jersey-media-multipart:3.0.2' 
    implementation 'org.glassfish.tyrus.bundles:tyrus-standalone-client:1.15'

    implementation 'io.swagger.core.v3:swagger-annotations:2.2.10'

    implementation 'commons-io:commons-io:2.11.0'
    implementation 'org.java-websocket:Java-WebSocket:1.5.2'

    implementation 'com.knuddels:jtokkit:0.6.1'
    implementation 'org.json:json:20171018'
    
    implementation 'com.nimbusds:oauth2-oidc-sdk:10.4'

    implementation 'org.web3j:core:5.0.0'

    implementation 'javax.ws.rs:javax.ws.rs-api:2.1.1'
	implementation 'javax.websocket:javax.websocket-api:1.1'

    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.8.20'

    implementation('org.apache.commons:commons-dbcp2:2.9.0'){
    exclude module: "asm"
    exclude module: "asm-commons"
        }

    // Use JUnit test framework.
    testImplementation "junit:junit:4.13.2"
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
	// testImplementation 'org.springframework.security:spring-security-test'
}


configurations {
    // This ensures las2peer is available in the tests, but won't be bundled
    testImplementation.extendsFrom compileOnly
}

jar {
    manifest {
        attributes "Main-Class": "${project.property('service.name')}.${project.property('service.class')}"
        attributes "Library-Version": "${project.property('service.version')}"
        attributes "Library-SymbolicName": "${project.property('service.name')}"
    }

    from { (configurations.runtimeClasspath).collect { it.isDirectory() ? it : zipTree(it) } } {
        // Exclude signatures to be able to natively bundle signed jars
        exclude 'META-INF/*.RSA', 'META-INF/*.SF', 'META-INF/*.DSA'
    }
    duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
}

application {
    // Define the main class for the application.
    mainClass = "${project.property('service.name')}.${project.property('service.class')}"

    group = "${project.property('service.name')}"
    archivesBaseName = group

    version = "${project.property('service.version')}"
    sourceCompatibility = "${project.property('java.version')}"
    targetCompatibility = "${project.property('java.version')}"
}

// put all .jar files into export/jars folder
tasks.withType(Jar) {
    destinationDirectory = file("$projectDir/export/jars")
}

javadoc {
    destinationDir = file("$projectDir/export/doc")
}

build.dependsOn "javadoc"

compileJava {
    dependsOn "copyMain"
}

compileTestJava {
    dependsOn "copyTest"
}

// Copies .xml files into build directory
task copyMain(type: Copy) {
    from "src/main/java"
    include "**/*.xml"
    into "$buildDir/classes/java/main"
}

// Copies .xml files into build directory
task copyTest(type: Copy) {
    from "src/test/java"
    include "**/*.xml"
    into "$buildDir/classes/java/test"
}

// These two tasks restore the build and runtime environment used
// in the ant environment
task copyJar(type: Copy) {
    from jar // here it automatically reads jar file produced from jar task
    into "$rootDir/service"
}

task copyToLib(type: Copy) {
    from configurations.compileClasspath
    into "$rootDir/lib"
}

build.dependsOn copyJar
build.dependsOn copyToLib

// task startscripts {
//     new File("$rootDir/bin", "start_network.sh").text = """#!/bin/bash

// # this script is autogenerated by 'gradle startscripts'

// java -cp "lib/*" --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED OpenAIServiceApplication uploadStartupDirectory startService\\(\\'${project.property('service.name')}.${project.property('service.class')}@${project.property('service.version')}\\'\\) startWebConnector interactive
// """ 
//     new File("$rootDir/bin", "start_network.bat").text = """:: this script is autogenerated by 'gradle startscripts'

// %~d0
// cd %~p0
// cd ..
// set BASE=%CD%
// set CLASSPATH="%BASE%/lib/*;"
// set ADD_OPENS=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED

// java -cp %CLASSPATH% %ADD_OPENS% OpenAIServiceApplication uploadStartupDirectory startService\\(\\'${project.property('service.name')}.${project.property('service.class')}@${project.property('service.version')}\\'\\) startWebConnector interactive

// pause
// """
// }

// build.dependsOn "startscripts"

task deleteStartup {

        file("$rootDir/etc/startup").deleteDir()
    
}

build.dependsOn "deleteStartup"

clean.doLast {
    file("$rootDir/tmp").deleteDir()
    file("$rootDir/lib").deleteDir()
    file("$rootDir/servicebundle").deleteDir()
    file("$rootDir/service").deleteDir()
    file("$rootDir/etc/startup").deleteDir()
    file("$projectDir/export").deleteDir()
}

task cleanAll {
    dependsOn "clean"

    doLast {
        file("$rootDir/log").deleteDir()
        file("$rootDir/node-storage").deleteDir()
    }
}

test {
    workingDir = file("$rootDir")
}

// configuration for eclipse (this allows to import the template project as a gradle project in eclipse without any problems)
eclipse {
    classpath {
      file {
            whenMerged {
                // change output directory for test, main, resources and default
                def main = entries.find { it.path == "src/main/java" }
                main.output = "output/main"

                def test = entries.find { it.path == "src/test/java" }
                test.output = "output/test"

                def defaultEntry = entries.find { it.kind == "output" && it.path == "bin/default" }
                defaultEntry.path = "output/default"
            }
        }
    }
}