spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.las2peer.org/auth/realms/main
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://auth.las2peer.org/auth/realms/main/protocol/openid-connect/certs
jwt.auth.converter.resource-id=spring-rest-api
jwt.auth.converter.principle-attribute=user