service.name=services.openAIService
service.class=OpenAIServiceApplication
service.version=2.0.0
java.version=17

springdoc.swagger-ui.path=/api-doc
springdoc.api-docs.path=/swagger.json

springdoc.packages-to-scan=services.OpenAIServiceController
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true